{
 "title": "Observability demo app",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "statusCode",
    "label": "Status Code",
    "query": "label_values(http_request_duration_seconds_bucket, code)"
   }
  ]
 },
 "panels": [
  {
   "title": "$statusCode Request duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "repeat": "statusCode",
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_bucket{app=\"observability-demo-app\", code=~\"$statusCode\" }) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Errors on logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"observability-demo-app\"}[2m] |= \"level=error\")) by (pod)"
    }
   ]
  }
 ]
}
{
 "title": "Grafana Internals",
 "description": "Grafana Internal Metics Dashboards",
 "tags": [ "grafana" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(grafana_build_info,pod)"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "label_values(grafana_build_info{pod=\"$pod\"}, version)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"$pod\"} * 1000"
    }
   ]
  },
  {
   "title": "Organisation Count",
   "type": "singlestat",
   "description": "total amount of orgs",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "singlestat",
   "description": "total amount of users",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafana_stat_total_users{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Dashboard Count",
   "type": "singlestat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Average CPU Usage [$interval]",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{pod=\"$pod\"}[$interval]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage [$interval]",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{pod=\"$pod\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Responce Codes and Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Response Statuses",
   "type": "graph",
   "description": "http response status",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafana_api_response_status_total{pod=\"$pod\"}",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "grafana_page_response_status_total{pod=\"$pod\"}",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "grafana_proxy_response_status_total{pod=\"$pod\"}",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "HTTP Req/Resp Details",
   "type": "graph",
   "description": "http request counter",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_total{pod=\"$pod\"}",
     "legendFormat": "{{handler}} - {{method}} - {{statuscode}}"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "graph",
   "description": "api login counters",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafana_api_login_post_total{pod=\"$pod\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "grafana_api_login_oauth_total{pod=\"$pod\"}",
     "legendFormat": "OAuth"
    }
   ]
  },
  { "title": "Dataproxy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Dataproxy Request Quantiles",
   "type": "graph",
   "description": "summary for dataproxy request duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{pod=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5 "
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{pod=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dataproxy Request Avg [$interval]",
   "type": "graph",
   "description": "average dataproxy request duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dataproxy_request_all_milliseconds_sum{pod=\"$pod\"}[$interval]) / rate(grafana_api_dataproxy_request_all_milliseconds_count{pod=\"$pod\"}[$interval])",
     "legendFormat": "Average Requests Duration"
    }
   ]
  },
  { "title": "Dashboard Get Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard get duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{pod=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{pod=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Avg [$interval]",
   "type": "graph",
   "description": "average dashboard get duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{pod=\"$pod\"}[$interval]) / rate(grafana_api_dashboard_get_milliseconds_count{pod=\"$pod\"}[$interval])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Save Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard save duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{pod=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{pod=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Avg [$interval]",
   "type": "graph",
   "description": "average dashboard save duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{pod=\"$pod\"}[$interval]) / rate(grafana_api_dashboard_save_milliseconds_count{pod=\"$pod\"}[$interval])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Search Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard search duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{pod=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{pod=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Avg [$interval]",
   "type": "graph",
   "description": "average dashboard search duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{pod=\"$pod\"}[$interval]) / rate(grafana_api_dashboard_search_milliseconds_count{pod=\"$pod\"}[$interval])",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}
{
 "title": "Loki & Promtail",
 "description": "Loki and Promtail metrics.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\"(loki|promtail)\"}"
    }
   ]
  },
  {
   "title": "Loki's stored chunk entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(loki_ingester_chunk_entries_count[5m])"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"(loki|promtail)\"}[1m] |= \"error\")) by (pod)"
    }
   ]
  },
  {
   "title": "Number of bytes total by promtail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (promtail_file_bytes_total{instance=~\".*\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Number of bytes encoded and ready to send by Promtail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (promtail_encoded_bytes_total{pod=~'.*'}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}